const itemImageMap = {
    "Adaptive Helm": "/images/items/adaptivehelm.avif",
    "Archangel's Staff": "/images/items/archangelsstaff.avif",
    "Bloodthirster": "/images/items/bloodthirster.avif",
    "Blue Buff": "/images/items/bluebuff.avif",
    "Bramble Vest": "/images/items/bramblevest.avif",
    "Crownguard": "/images/items/crownguard.avif",
    "Deathblade": "/images/items/deathblade.avif",
    "Dragon's Claw": "/images/items/dragonsclaw.avif",
    "Edge of Night": "/images/items/edgeofnight.avif",
    "Evenshroud": "/images/items/evenshroud.avif",
    "Gargoyle Stoneplate": "/images/items/gargoylestoneplate.avif",
    "Giant Slayer": "/images/items/giantslayer.avif",
    "Guardbreaker": "/images/items/guardbreaker.avif",
    "Guinsoo's Rageblade": "/images/items/guinsoosrageblade.avif",
    "Hand of Justice": "/images/items/handofjustice.avif",
    "Hextech Gunblade": "/images/items/hextechgunblade.avif",
    "Infinity Edge": "/images/items/infinityedge.avif",
    "Ionic Spark": "/images/items/ionicspark.avif",
    "Jeweled Gauntlet": "/images/items/jeweledgauntlet.avif",
    "Last Whisper": "/images/items/lastwhisper.avif",
    "Morellonomicon": "/images/items/morellonomicon.avif",
    "Nashor's Tooth": "/images/items/nashorstooth.avif",
    "Protector's Vow": "/images/items/protectorsvow.avif",
    "Quicksilver": "/images/items/quicksilver.avif",
    "Rabadon's Deathcap": "/images/items/rabadonsdeathcap.avif",
    "Red Buff": "/images/items/redbuff.avif",
    "Redemption": "/images/items/redemption.avif",
    "Runaan's Hurricane": "/images/items/runaanshurricane.avif",
    "Spear of Shojin": "/images/items/spearofshojin.avif",
    "Statikk Shiv": "/images/items/statikkshiv.avif",
    "Steadfast Heart": "/images/items/steadfastheart.avif",
    "Sterak's Gage": "/images/items/steraksgage.avif",
    "Sunfire Cape": "/images/items/sunfirecape.avif",
    "Thief's Gloves": "/images/items/thiefsgloves.avif",
    "Titan's Resolve": "/images/items/titansresolve.avif",
    "Warmog's Armor": "/images/items/warmogsarmor.avif",
    // Fallback image
    default: "/images/items/default.avif",
  };
  
  export default itemImageMap;
  