const itemImageMap = {
    "Adaptive Helm": "/images/items/TFT_Item_AdaptiveHelm.png",
    "Archangel's Staff": "/images/items/TFT_Item_ArchangelsStaff.png",
    "Bloodthirster": "/images/items/TFT_Item_Bloodthirster.png",
    "Blue Buff": "/images/items/TFT_Item_BlueBuff.png",
    "Bramble Vest": "/images/items/TFT_Item_BrambleVest.png",
    "Crownguard": "/images/items/TFT_Item_Crownguard.png",
    "Deathblade": "/images/items/TFT_Item_Deathblade.png",
    "Dragon's Claw": "/images/items/TFT_Item_DragonsClaw.png",
    "Edge of Night": "/images/items/TFT_Item_GuardianAngel.png",
    "Evenshroud": "/images/items/TFT_Item_SpectralGauntlet.png",
    "Gargoyle Stoneplate": "/images/items/TFT_Item_GargoyleStoneplate.png",
    "Giant Slayer": "/images/items/TFT_Item_MadredsBloodrazor.png",
    "Guardbreaker": "/images/items/TFT_Item_PowerGauntlet.png",
    "Guinsoo's Rageblade": "/images/items/TFT_Item_GuinsoosRageblade.png",
    "Hand Of Justice": "/images/items/TFT_Item_UnstableConcoction.png",
    "Hextech Gunblade": "/images/items/TFT_Item_HextechGunblade.png",
    "Infinity Edge": "/images/items/TFT_Item_InfinityEdge.png",
    "Ionic Spark": "/images/items/TFT_Item_IonicSpark.png",
    "Jeweled Gauntlet": "/images/items/TFT_Item_JeweledGauntlet.png",
    "Last Whisper": "/images/items/TFT_Item_LastWhisper.png",
    "Morellonomicon": "/images/items/TFT_Item_Morellonomicon.png",
    "Nashor's Tooth": "/images/items/TFT_Item_Leviathan.png",
    "Protector's Vow": "/images/items/TFT_Item_FrozenHeart.png",
    "Quicksilver": "/images/items/TFT_Item_Quicksilver.png",
    "Rabadon's Deathcap": "/images/items/TFT_Item_RabadonsDeathcap.png",
    "Red Buff": "/images/items/TFT_Item_RapidFireCannon.png",
    "Spirit Visage": "/images/items/TFT_Item_Redemption.png",
    "Kraken's Fury": "/images/items/TFT_Item_RunaansHurricane.png",
    "Spear of Shojin": "/images/items/TFT_Item_SpearOfShojin.png",
    "Void Staff": "/images/items/TFT_Item_StatikkShiv.png",
    "Steadfast Heart": "/images/items/TFT_Item_NightHarvester.png",
    "Sterak's Gage": "/images/items/TFT_Item_SteraksGage.png",
    "Striker's Flail": "/images/items/TFT_Item_PowerGauntlet.png",
    "Sunfire Cape": "/images/items/TFT_Item_RedBuff.png",
    "Thief's Gloves": "/images/items/TFT_Item_ThiefsGloves.png",
    "Titanic Hydra": "/images/items/TFT_Item_TitanicHydra.png",
    "Titan's Resolve": "/images/items/TFT_Item_TitansResolve.png",
    "Warmog's Armor": "/images/items/TFT_Item_WarmogsArmor.png",
    "Zeke's Herald": "/images/items/TFT_Item_ZekesHerald.png",
    "Zephyr": "/images/items/TFT_Item_Zephyr.png",
    // Fallback image
    default: "/images/items/default.avif",
  };
  
  export default itemImageMap;
  