const unitLevelMap = {
    Aatrox: 1,
    Ezreal: 1,
    Garen: 1,
    Gnar: 1,
    Kalista: 1,
    Kayle: 1,
    Kennen: 1,
    Lucian: 1,
    Malphite: 1,
    Naafiri: 1,
    Rell: 1,
    Sivir: 1,
    Syndra: 1,
    Zac: 1,
    "Dr. Mundo": 2,
    Gangplank: 2,
    Janna: 2,
    Jhin: 2,
    "Kai'sa": 2,
    Katarina: 2,
    Kobuko: 2,
    Lux: 2,
    Rakan: 2,
    Shen: 2,
    Vi: 2,
    Xayah: 2,
    "Xin Zhao": 2,
    Ahri: 3,
    Caitlyn: 3,
    Darius: 3,
    Jayce: 3,
    "Kog'Maw": 3,
    Rammus: 3,
    Smolder: 3,
    Malzahar: 3,
    Neeko: 3,
    Senna: 3,
    Swain: 3,
    Udyr: 3,
    Viego: 3,
    Yasuo: 3,
    Ziggs: 3,
    Akali: 4,
    Ashe: 4,
    "Jarvan IV": 4,
    Jinx: 4,
    "K'Sante": 4,
    Karma: 3,
    Leona: 4,
    Poppy: 4,
    Samira: 4,
    Sett: 4,
    Volibear: 4,
    Yuumi: 4,
    Braum: 5,
    Gwen: 5,
    "Lee Sin": 5,
    Seraphine: 5,
    "Twisted Fate": 5,
    Varus: 5,
    Yone: 5,
    Zyra: 5,
  };
  
  export default unitLevelMap;