const unitImageMap = {
    Aatrox: "/images/units/aatrox.avif",
    Ahri: "/images/units/ahri.avif",
    Akali: "/images/units/akali.avif",
    Ashe: "/images/units/ashe.avif",
    Braum: "/images/units/braum.avif",
    Caitlyn: "/images/units/caitlyn.avif",
    Darius: "/images/units/darius.avif",
    "Dr Mundo": "/images/units/drmundo.avif",
    Ezreal: "/images/units/ezreal.avif",
    Gangplank: "/images/units/gangplank.avif",
    Garen: "/images/units/garen.avif",
    Gnar: "/images/units/gnar.avif",
    Gwen: "/images/units/gwen.avif",
    Janna: "/images/units/janna.avif",
    "Jarvan IV": "/images/units/jarvaniv.avif",
    Jayce: "/images/units/jayce.avif",
    Jhin: "/images/units/jhin.avif",
    Jinx: "/images/units/jinx.avif",
    "Kai'Sa": "/images/units/kaisa.avif",
    Klista: "/images/units/kalista.avif",
    Karma: "/images/units/karma.avif",
    Katarina: "/images/units/katarina.avif",
    Kayle: "/images/units/kayle.avif",
    Kennen: "/images/units/kennen.avif",
    Kobuko: "/images/units/kobuko.avif",
    "Kog'Maw": "/images/units/kogmaw.avif",
    "K'Sante": "/images/units/ksante.avif",
    "Lee Sin": "/images/units/leesin.avif",
    Leona: "/images/units/leona.avif",
    Lucian: "/images/units/lucian.avif",
    Lux: "/images/units/lux.avif",
    Malphite: "/images/units/malphite.avif",
    Malzahar: "/images/units/malzahar.avif",
    Naafiri: "/images/units/naafiri.avif",
    Neeko: "/images/units/neeko.avif",
    Poppy: "/images/units/poppy.avif",
    Rakan: "/images/units/rakan.avif",
    Rammus: "/images/units/rammus.avif",
    Rell: "/images/units/rell.avif",
    Ryze: "/images/units/ryze.avif",
    Samira: "/images/units/samira.avif",
    Senna: "/images/units/senna.avif",
    Seraphine: "/images/units/seraphine.avif",
    Sett: "/images/units/sett.avif",
    Shen: "/images/units/shen.avif",
    Sivir: "/images/units/sivir.avif",
    Smolder: "/images/units/smolder.avif",
    Swain: "/images/units/swain.avif",
    Syndra: "/images/units/syndra.avif",
    "Twisted Fate": "/images/units/twistedfate.avif",
    Udyr: "/images/units/udyr.avif",
    Varus: "/images/units/varus.avif",
    Vi: "/images/units/vi.avif",
    Viego: "/images/units/viego.avif",
    Volibear: "/images/units/volibear.avif",
    Xayah: "/images/units/xayah.avif",
    "Xin Zhao": "/images/units/xinzhao.avif",
    Yasuo: "/images/units/yasuo.avif",
    Yone: "/images/units/yone.avif",
    Yuumi: "/images/units/yuumi.avif",
    Zac: "/images/units/zac.avif",
    Ziggs: "/images/units/ziggs.avif",
    Zyra: "/images/units/zyra.avif",
    // Fallback image
    default: "/images/units/default.avif",
  };
  
  export default unitImageMap;