const unitImageMap = {
    Amumu: "/images/units/amumu.avif",
    Darius: "/images/units/darius.avif",
    Draven: "/images/units/draven.avif",
    Irelia: "/images/units/irelia.avif",
    Lux: "/images/units/lux.avif",
    Maddie: "/images/units/maddie.avif",
    Morgana: "/images/units/morgana.avif",
    Powder: "/images/units/powder.avif",
    Singed: "/images/units/singed.avif",
    Steb: "/images/units/steb.avif",
    Trundle: "/images/units/trundle.avif",
    Vex: "/images/units/vex.avif",
    Violet: "/images/units/violet.avif",
    Zyra: "/images/units/zyra.avif",
    Akali: "/images/units/akali.avif",
    Camille: "/images/units/camille.avif",
    Leona: "/images/units/leona.avif",
    Nocturne: "/images/units/nocturne.avif",
    Rell: "/images/units/rell.avif",
    "Renata Glasc": "/images/units/renataglasc.avif",
    Sett: "/images/units/sett.avif",
    Tristana: "/images/units/tristana.avif",
    Urgot: "/images/units/urgot.avif",
    Vander: "/images/units/vander.avif",
    Vladimir: "/images/units/vladimir.avif",
    Zeri: "/images/units/zeri.avif",
    Ziggs: "/images/units/ziggs.avif",
    Blitzcrank: "/images/units/blitzcrank.avif",
    Cassiopeia: "/images/units/cassiopeia.avif",
    Ezreal: "/images/units/ezreal.avif",
    Gangplank: "/images/units/gangplank.avif",
    "Kog'Maw": "/images/units/kogmaw.avif",
    Loris: "/images/units/loris.avif",
    "Nunu Willump": "/images/units/nunuwillump.avif",
    Renni: "/images/units/renni.avif",
    Scar: "/images/units/scar.avif",
    Smeech: "/images/units/smeech.avif",
    Swain: "/images/units/swain.avif",
    "Twisted Fate": "/images/units/twistedfate.avif",
    Ambessa: "/images/units/ambessa.avif",
    Corki: "/images/units/corki.avif",
    "Dr Mundo": "/images/units/drmundo.avif",
    Ekko: "/images/units/ekko.avif",
    Elise: "/images/units/elise.avif",
    Garen: "/images/units/garen.avif",
    Heimerdinger: "/images/units/heimerdinger.avif",
    Illaoi: "/images/units/illaoi.avif",
    Nami: "/images/units/nami.avif",
    Silco: "/images/units/silco.avif",
    Twitch: "/images/units/twitch.avif",
    Vi: "/images/units/vi.avif",
    Zoe: "/images/units/zoe.avif",
    Caitlyn: "/images/units/caitlyn.avif",
    Jayce: "/images/units/jayce.avif",
    Jinx: "/images/units/jinx.avif",
    LeBlanc: "/images/units/leblanc.avif",
    Malzahar: "/images/units/malzahar.avif",
    Mordekaiser: "/images/units/mordekaiser.avif",
    Rumble: "/images/units/rumble.avif",
    Sevika: "/images/units/sevika.avif",
    Mel: "/images/units/mel.avif",
    Viktor: "/images/units/viktor.avif",
    Warwick: "/images/units/warwick.avif",
    // Fallback image
    default: "/images/units/default.avif",
  };
  
  export default unitImageMap;