const unitLevelMap = {
    Amumu: 1,
    Darius: 1,
    Draven: 1,
    Irelia: 1,
    Lux: 1,
    Maddie: 1,
    Morgana: 1,
    Powder: 1,
    Singed: 1,
    Steb: 1,
    Trundle: 1,
    Vex: 1,
    Violet: 1,
    Zyra: 1,
    Akali: 2,
    Camille: 2,
    Leona: 2,
    Nocturne: 2,
    Rell: 2,
    "Renata Glasc": 2,
    Sett: 2,
    Tristana: 2,
    Urgot: 2,
    Vander: 2,
    Vladimir: 2,
    Zeri: 2,
    Ziggs: 2,
    Blitzcrank: 3,
    Cassiopeia: 3,
    Ezreal: 3,
    Gangplank: 3,
    "Kog'Maw": 3,
    Loris: 3,
    "Nunu Willump": 3,
    Renni: 3,
    Scar: 3,
    Smeech: 3,
    Swain: 3,
    "Twisted Fate": 3,
    Ambessa: 4,
    Corki: 4,
    "Dr Mundo": 4,
    Ekko: 4,
    Elise: 4,
    Garen: 4,
    Heimerdinger: 4,
    Illaoi: 4,
    Nami: 3,
    Silco: 4,
    Twitch: 4,
    Vi: 4,
    Zoe: 4,
    Caitlyn: 5,
    Jayce: 5,
    Jinx: 5,
    LeBlanc: 5,
    Malzahar: 5,
    Mordekaiser: 5,
    Rumble: 5,
    Sevika: 5,
    Mel: 6,
    Viktor: 6,
    Warwick: 6,
  };
  
  export default unitLevelMap;